export const ErrorCodes = {
  DEAD_LOCK: "40P01",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  FAILED_TO_CREATE_ENTRY: "FAILED_TO_CREATE_ENTRY",
  FAILED_TO_CREATE_JOB: "FAILED_TO_CREATE_JOB",
  JOB_UPDATED_FAILED: "UPDATE_JOB_FAILED",
  FAILED_TO_CREATE_ACCOUNT: "FAILED_TO_CREATE_ACCOUNT",
  FAILED_TO_GET_JOB: "FAILED_TO_GET_JOB",
  JOB_IS_COMPLETED: "JOB_IS_COMPLETED",
  JOB_IS_FAILED: "JOB_IS_FAILED",
  UNDEFINED_JOB: "UNDEFINED_JOB",
  UNKNOWN: "UNKNOWN",
};
