export const ErrorCodes = {
  DEAD_LOCK: "40P01",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  FAILED_TO_CREATE_ENTRY: "FAILED_TO_CREATE_ENTRY",
  FAILED_TO_CREATE_JOB: "FAILED_TO_CREATE_JOB",
  JOB_UPDATED_FAILED: "UPDATE_JOB_FAILED",
  FAILED_TO_CREATE_ACCOUNT: "FAILED_TO_CREATE_ACCOUNT",
  FAILED_TO_GET_JOB: "FAILED_TO_GET_JOB",
  JOB_IS_COMPLETED: "JOB_IS_COMPLETED",
  JOB_IS_FAILED: "JOB_IS_FAILED",
  UNDEFINED_JOB: "UNDEFINED_JOB",
  UNKNOWN: "UNKNOWN",
  // App Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
};

export const ErrorStrategyCodes = {
  RETRY_JOB: "RETRY_JOB",
  CANCEL_JOB: "CANCEL_JOB",
  UNKNOWN: "UNKNOWN",
};
