export const ErrorCodes = {
  DEAD_LOCK: "40P01",
  INSUFFICIENT_BALANCE: "INSUFFICIENT_BALANCE",
  FAILED_TO_CREATE_ENTRY: "FAILED_TO_CREATE_ENTRY",
  FAILED_TO_CREATE_JOB: "FAILED_TO_CREATE_JOB",
  JOB_UPDATED_FAILED: "UPDATE_JOB_FAILED",
  FAILED_TO_CREATE_ACCOUNT: "FAILED_TO_CREATE_ACCOUNT",
  FAILED_TO_GET_JOB: "FAILED_TO_GET_JOB",
  JOB_IS_COMPLETED: "JOB_IS_COMPLETED",
  JOB_IS_FAILED: "JOB_IS_FAILED",
  UNDEFINED_JOB: "UNDEFINED_JOB",
  UNKNOWN: "UNKNOWN",
  // App Errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  BAD_REQUEST: "BAD_REQUEST",
  NOT_FOUND: "NOT_FOUND",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
};

export enum ErrorStatusCode {
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  CONFLICT = 409,
  UNPROCESSABLE_ENTITY = 422,
  TOO_MANY_REQUESTS = 429,

  // 5xx Server Errors
  INTERNAL_SERVER_ERROR = 500,
  NOT_IMPLEMENTED = 501,
  BAD_GATEWAY = 502,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export const ErrorStrategyCodes = {
  RETRY_JOB: "RETRY_JOB",
  CANCEL_JOB: "CANCEL_JOB",
  UNKNOWN: "UNKNOWN",
};
